"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](bluegreen)\
$os\
$username\
[](bg:thickblue fg:bluegreen)\
$directory\
[](bg:paleblue fg:thickblue)\
$git_branch\
$git_status\
[](fg:paleblue bg:deepblue)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:deepblue bg:sapphire)\
$conda\
[](fg:sapphire bg:darkblue)\
$time\
[ ](fg:darkblue)\
$cmd_duration\
$line_break\
$character"""

palette = 'catppuccin_mocha'

[os]
disabled = false
style = "bg:bluegreen fg:mytext"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:bluegreen fg:mytext"
style_root = "bg:bluegreen fg:mytext"
format = '[ $user]($style)'

[directory]
style = "bg:thickblue fg:mytext"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:paleblue"
format = '[[ $symbol $branch ](fg:mytext bg:paleblue)]($style)'

[git_status]
style = "bg:paleblue"
format = '[[($all_status$ahead_behind )](fg:mytext bg:paleblue)]($style)'

[nodejs]
symbol = ""
style = "bg:deepblue"
format = '[[ $symbol( $version) ](fg:mytext bg:deepblue)]($style)'

[c]
symbol = " "
style = "bg:deepblue"
format = '[[ $symbol( $version) ](fg:mytext bg:deepblue)]($style)'

[rust]
symbol = ""
style = "bg:deepblue"
format = '[[ $symbol( $version) ](fg:mytext bg:deepblue)]($style)'

[golang]
symbol = ""
style = "bg:deepblue"
format = '[[ $symbol( $version) ](fg:mytext bg:deepblue)]($style)'

[php]
symbol = ""
style = "bg:deepblue"
format = '[[ $symbol( $version) ](fg:mytext bg:deepblue)]($style)'

[java]
symbol = " "
style = "bg:deepblue"
format = '[[ $symbol( $version) ](fg:mytext bg:deepblue)]($style)'

[kotlin]
symbol = ""
style = "bg:deepblue"
format = '[[ $symbol( $version) ](fg:mytext bg:deepblue)]($style)'

[haskell]
symbol = ""
style = "bg:deepblue"
format = '[[ $symbol( $version) ](fg:mytext bg:deepblue)]($style)'

[python]
symbol = ""
style = "bg:deepblue"
format = '[[ $symbol( $version)(\($virtualenv\)) ](fg:mytext bg:deepblue)]($style)'

[docker_context]
symbol = ""
style = "bg:sapphire"
format = '[[ $symbol( $context) ](fg:mytext bg:sapphire)]($style)'

[conda]
symbol = "  "
style = "fg:mytext bg:sapphire"
format = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%H:%M:%S"
style = "bg:darkblue"
format = '[[  $time ](fg:mytext bg:darkblue)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:deepblue)'
error_symbol = '[❯](bold fg:bluegreen)'
vimcmd_symbol = '[❮](bold fg:deepblue)'
vimcmd_replace_one_symbol = '[❮](bold fg:darkblue)'
vimcmd_replace_symbol = '[❮](bold fg:darkblue)'
vimcmd_visual_symbol = '[❮](bold fg:paleblue)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "bg:darkblue"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
bluegreen = "#244880"
maroon = "#eba0ac"
thickblue = "#292470"
paleblue = "#2f5194"
deepblue = "#2d2e91"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#0c2f3d"
blue = "#89b4fa"
darkblue = "#161e50"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
mytext = "#77bda6"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
bluegreen = "#e78284"
maroon = "#ea999c"
thickblue = "#ef9f76"
paleblue = "#e5c890"
deepblue = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
darkblue = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
mytext = "#232634"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
bluegreen = "#d20f39"
maroon = "#e64553"
thickblue = "#fe640b"
paleblue = "#df8e1d"
deepblue = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
darkblue = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
mytext = "#dce0e8"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
bluegreen = "#ed8796"
maroon = "#ee99a0"
thickblue = "#f5a97f"
paleblue = "#eed49f"
deepblue = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
darkblue = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
mytext = "#181926"
